### ISSUE TITLE
Error for Facet Filter Component

### ISSUE THREAD

**Issue by mrbensan** [org-scn-design-studio-community/sdkpackage#47] opened 2015-04-09 13:12 UTC
A script error occurs with the Facet Filter when attempting to implement a cascading filter for an Initial View that does not contain dimensions.

Initial View:
![initialviewnomeasures](https://cloud.githubusercontent.com/assets/6189517/7067144/6615d78a-df0c-11e4-8624-272e97f10682.png)

Properties:
![properties2](https://cloud.githubusercontent.com/assets/6189517/7067159/79df9594-df0c-11e4-922c-139bae734a07.png)

Error Log:
![errorlog](https://cloud.githubusercontent.com/assets/6189517/7067165/879e72cc-df0c-11e4-955f-b9ceb91015fc.png)

Application:
![dsapplication](https://cloud.githubusercontent.com/assets/6189517/7067230/f4e85f8c-df0c-11e4-9476-4bfed626ea7a.png)

OnStartup Script:
FACETFILTER_1.reloadDataSource();
FACETFILTER_1.reloadSelection();

On Result Set Changed Script:
FACETFILTER_1.reloadDataSource();
FACETFILTER_1.reloadSelection();

**Comment by KarolKalisz** [comment] 2015-04-09 15:27
Hi Mustafa,

the isse is due to parsing of this array - your " character is not correct (it is a bit italic, I think it cannot be correctly parsed). check this entry on JSON parser: http://jsonformatter.curiousconcept.com/

this one should be correct:
"

The issue will be solved as soon we can generate also APS for array (on the way).

now, to the general topic - the cascade filter.

I think I have not fully described the properties. when you use the "Zero-Values Mode" with "Hide" then members which do not have a value will be not displayed - and in your case, as you have no dimensions in resultset - this means all, as value is read from resultset. This means, you can make cascading filter with this property ONLY when you use dimensions from resultset.

the second option is to reload data source every time, exactly like you do, but for this, you need to allow showing also Zero-Values, so the property must be on "Show".

helps?
Karol

**Comment by KarolKalisz** [comment] 2015-04-09 17:55
Mustafa, preview is updated with a fix for the "Hide" issue.

**Comment by KarolKalisz** [comment] 2015-12-23 09:57
closing as the issue is fixed.

**Closed by KarolKalisz** 2015-12-23 09:57 UTC
