### ISSUE TITLE
Embedded iframe issue after BO upgrade to BO 4.2 Sp4

### ISSUE THREAD

**Issue by sreenichinta** [org-scn-design-studio-community/sdkpackage#168] opened 2017-06-28 05:56 UTC
Hi,
I have same problem occur after upgrade my BO server to 4.2 Sp4..

@MartinPankraz 

#113 #142 
Martin, 
We need you help.

Thanks,
Sreeni.

**Comment by sreenichinta** [comment] 2017-06-28 06:01
Martin,

"&noDetailsPanel=true" is not working as we discussed earlier after BO upgrade.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment] 2017-06-28 06:50
Hi Sreeni,

We didn't change anything. You will need to check if your OpenDocument link works as expected regarding the option you mentioned, especially if it worked before. Apart from that the IFrame works as it did before. If you have problems you will have to talk to your SAP basis.

Kind regards
Martin

**Comment by sreenichinta** [comment] 2017-06-28 10:11
Martin,
Today we have downloaded new version & install in both server & client system with following settings.. it is keep on rendering even after SDK loads.

note: identified 2 new extra properties like sandbox... can you please your end for BO 4.2 SP4 version 

Version:
![image](https://user-images.githubusercontent.com/20972340/27631917-cfcfdc2c-5c17-11e7-8ed3-e033d3dcbf4c.png)

Settings:
![image](https://user-images.githubusercontent.com/20972340/27631935-de4719d2-5c17-11e7-895f-837b1d508f97.png)

issue:
![image](https://user-images.githubusercontent.com/20972340/27631973-f06167e4-5c17-11e7-83f9-fa73d4cf62c7.png)

**Comment by MartinPankraz** [comment] 2017-06-28 10:50
Hi Sreeni,

Unfortunately I have no server available that fullfills the requirements to reproduce your problem. Apart from that it is more likely that you have another issue. Like on the tickets before, please troubleshoot the http calls and check the browser's developer tools for errors.

The attributes mentioned were present already before. You can check the issues you linked.

Kind regards
Martin

**Comment by sreenichinta** [comment] 2017-06-29 06:55
Martin,
New problem arises after i use new SDK file & i don't find errors apart from style sheet in HTTP calls

![image](https://user-images.githubusercontent.com/20972340/27675017-e61088c0-5cc5-11e7-861e-56c3169a7b5d.png)

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment] 2017-06-29 07:25
Hi Sreeni,

I don't see any errors there. All http calls finsihed with code 200 (OK). Unfortunately I cannot help you with any server issues that you might have. We only provide the IFrame. Communication in between windows is subject to browser security and your IT setup.

Kind regards
Martin

**Comment by sreenichinta** [comment] 2017-06-30 04:52
Martin,
Today i have observed 2 things 
1> If I set "_Explicitly set document domain_" = _true_ then dashboard keep on refreshing... 
2> If it set to _false_ then one time refresh finally replaces new dashboard which is calling in url property. 
I think last time we add "&noDetailsPanel=true" to main dashboard url which stops the second one. 
But after upgrade "&noDetailsPanel=true" is not working.

Do you have any work around solution.

![image](https://user-images.githubusercontent.com/20972340/27720943-ab7070da-5d7a-11e7-9a43-f62d4f05686f.png)

**Comment by MartinPankraz** [comment] 2017-06-30 06:57
Hi Sreeni,

I told you already in August last year that the url parameter "&noDetailsPanel=true" is not fixing or causing your problem. Last time it just appeared so because there was a bug in the OpenDocument link in BIP. Since that is probably fixed by now you experience issues again. So it seems your server setup for showing nested BO content was never correct. I cannot help you with that.

Judging from your screenshot the setup should be correct with "Explicitly set document domain" false and the relative URL path.

Is there anything else you would like to know regarding your problem? Otherwise I will close this ticket.

Kind regards
Martin

**Closed** 2017-08-03 11:51 UTC

**Comment by Andrew-Barlow** [comment] 2018-03-08 16:50
Hi Martin,
After upgrade to 4.2 we too are having major issues with navigation . Please can you tell me where to get the latest ver of the embedded control with the extra props in it so I can test it to see if it fixes my problem?
The inspector is telling me.....Uncaught DOMException: Blocked a frame with origin "the url" from accessing a cross-origin frame.
Its weird because its same protocol, domain and port...

**Comment by MartinPankraz** [comment] 2018-03-08 16:55
Hi Andrew,

You can download the latest version for Lumira 2.x [here](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext).

Let me add that the code for the embedde Frame haven't been touched in a long time, so any issues are most probably coming from your upgrade.

Kind regards
Martin

**Comment by Andrew-Barlow** [comment] 2018-03-08 16:56
Will that version still work with DS 1.6 SP5 Martin?

**Comment by Andrew-Barlow** [comment] 2018-03-08 16:57
Sorry - should have followed the link before I asked....

**Comment by Andrew-Barlow** [comment] 2018-03-08 16:57
Thanks

**Comment by Andrew-Barlow** [comment] 2018-03-09 08:25
Martin - sticking to the subject of embedding or 'Launching' other url's or reports from inside DS - if it is that we are not maintaining the embedded control perhaps so much now - is this because of Lumira Designer 2.0? Are there better ways of achieving this in Lumira 2? I don't want to spend loads of time trying to fix something that would have a short life if there is a better way to achieve the same thing in 2.0?
I wont hold you to anything Martin - I am just after an opinion from somebody who know s the toolset inside out.
Thanks in advance..

**Comment by MartinPankraz** [comment] 2018-03-09 08:42
Hi Andrew,

IFrames are often problematic when it comes to embedding BO into BO due to the server settings and security policies. Alternatively SAP supports URL jumps from the APPLICATION object within Scripting.

Also there are APIs regarding the BO toolset (e.g. WebIntelligence and CR) that can be called to open reports using the navigational context from DesignStudio. 

Another line of thought would be the Report-to-Report interface (RRI), which can be defined on BW, to support jumps from querys for example. The context menu on DesignStudio/Lumira Designer will support that out of the box.

The only thing my embedded control does, is exposing the HTML IFrame tag to DesignStudio/LD with some extra functions to overcome some security policy problems like almost identical subdomains. So bottom line is that IFrame related problems are not something that I can fix.

Does this help with your research?

Kind regards
Martin

**Comment by Andrew-Barlow** [comment] 2018-03-09 09:40
Hi Martin,
Thanks - this has aligned a few things for me. 
I need to re-engineer the original solution away from frames etc. 

Thanks for your input and also replying so promptly.
All the best
